language: go

dist: trusty

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

addons:
  apt:
    packages:
    - php5-fpm
    - python3
    - python3.4-venv

env:
  global:
  - TEST_PHPFPM_PATH=/usr/sbin/php5-fpm

before_script:
  # for python3 tests
  - python3 -m venv myvenv
  - source myvenv/bin/activate
  - which python3 && python3 --version
  - which pip3 && pip3 --version
  - pip3 install -r example/python3/requirements.txt

script:
  - go test -v -race ./...
